// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTV94FNhfftqzcMFgsS6CyI-8dLBYlMtM',
    appId: '1:825880585012:web:c6a954f7d817fff7667b61',
    messagingSenderId: '825880585012',
    projectId: 'spacynotes',
    authDomain: 'spacynotes.firebaseapp.com',
    storageBucket: 'spacynotes.firebasestorage.app',
    measurementId: 'G-FC4LT924BE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfQuHrOY7s9j1Dnfa-QrSuf--sYlAAeCQ',
    appId: '1:825880585012:android:75cfdc41af59b78d667b61',
    messagingSenderId: '825880585012',
    projectId: 'spacynotes',
    storageBucket: 'spacynotes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoTOevxfpXRAkdQRMC1iQEVnfwt_20r80',
    appId: '1:825880585012:ios:9d8080472ace914e667b61',
    messagingSenderId: '825880585012',
    projectId: 'spacynotes',
    storageBucket: 'spacynotes.firebasestorage.app',
    iosBundleId: 'com.example.spacyNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoTOevxfpXRAkdQRMC1iQEVnfwt_20r80',
    appId: '1:825880585012:ios:9d8080472ace914e667b61',
    messagingSenderId: '825880585012',
    projectId: 'spacynotes',
    storageBucket: 'spacynotes.firebasestorage.app',
    iosBundleId: 'com.example.spacyNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTV94FNhfftqzcMFgsS6CyI-8dLBYlMtM',
    appId: '1:825880585012:web:005e0fb0ad08b090667b61',
    messagingSenderId: '825880585012',
    projectId: 'spacynotes',
    authDomain: 'spacynotes.firebaseapp.com',
    storageBucket: 'spacynotes.firebasestorage.app',
    measurementId: 'G-C426X3EXSJ',
  );
}
